BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "base_kluisjesrv" (
	"id"	integer NOT NULL,
	"kluisnummer"	varchar(200) NOT NULL,
	"naamvoluit"	varchar(200) NOT NULL,
	"gender"	varchar(200) NOT NULL,
	"email"	varchar(200) NOT NULL,
	"userid"	varchar(200) NOT NULL,
	"kluisje"	varchar(200) NOT NULL,
	"kastje"	varchar(18) NOT NULL,
	"topic"	varchar(18) NOT NULL,
	"col"	varchar(18) NOT NULL,
	"row"	varchar(18) NOT NULL,
	"verhuurd"	bool NOT NULL,
	"label"	varchar(18) NOT NULL,
	"type"	varchar(18) NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (1,'D001','Rinske Krabbe','Vrouw','r.krabbe@hetnet.nl','','D001','Dames 01','DDames','03','01',true,'D_01','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (2,'D004','Annemieke Rensink','Vrouw','aamrensink@gmail.com','','D004','Dames 04','DDames','04','01',true,'D_04','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (3,'D005','Annemarie van der Burg','Vrouw','cmeermin@airpost.net','','D005','Dames 05','DDames','06','01',true,'D_05','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (4,'D007','Vivian van der Kuil','Vrouw','vvanderkuil@me.com','','D007','Dames 07','DDames','07','01',true,'D_07','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (5,'D008','Wyke Ruedisulj','Vrouw','wyki24@gmail.com','','D008','Dames 08','DDames','08','01',true,'D_08','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (6,'D009','Petra de Leede','Vrouw','petradeleede@gmail.com','','D009','Dames 09','DDames','11','01',true,'D_09','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (7,'D012','Froukje Euwe','Vrouw','f_euwe@hotmail.com','','D012','Dames 12','DDames','12','01',true,'D_12','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (8,'D013','Miranda Rovers','Vrouw','miranda@miraud.nl','','D013','Dames 13','DDames','01','02',true,'D_13','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (9,'D014','Mimi Bröker-van Dongen','Vrouw','w.brokervandongen@upcmail.nl','','D014','Dames 14','DDames','02','02',true,'D_14','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (10,'D015','Maaike van Gulik-Rijlaarsdam','Vrouw','maaike@vangulik.org','','D015','Dames 15','DDames','03','02',true,'D_15','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (11,'D016','Lia Kaboord-Bartels','Vrouw','lkaboord@kpnmail.nl','','D016','Dames 16','DDames','06','02',true,'D_16','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (12,'D019','Nadine van Wijk','Vrouw','nadinevanwijk@gmail.com','','D019','Dames 19','DDames','07','02',true,'D_19','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (13,'D020','Ellen Beverdam','Vrouw','ebeverdam@xs4all.nl','','D020','Dames 20','DDames','08','02',true,'D_20','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (14,'D021','Natalie Cappaert','Vrouw','n.l.m.cappaert@gmail.com','','D021','Dames 21','DDames','10','02',true,'D_21','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (15,'D023','Birgitte Aertssen','Vrouw','birgitte.aertssen@gmail.com','','D023','Dames 23','DDames','11','02',true,'D_23','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (16,'D024','Willemijn Sprangers','Vrouw','willemijnsprangers@gmail.com','','D024','Dames 24','DDames','12','08',true,'D_24','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (17,'A025','Talitha van den Elst','Vrouw','t.elst@wxs.nl','','A025','Dames A-25','ADames','01','03',true,'A_A-25','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (18,'A026','Harmke van Dam','Vrouw','stapvdam@xs4all.nl','','A026','Dames A-26','ADames','02','03',true,'A_A-26','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (19,'A027','Anouk Rijs','Vrouw','anoukrijs@hotmail.com','','A027','Dames A-27','ADames','06','03',true,'A_A-27','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (20,'A031','Miranda Megens','Vrouw','miranda_megens@yahoo.com','','A031','Dames A-31','ADames','07','03',true,'A_A-31','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (21,'A032','Jessica van der Leij','Vrouw','jessica@ambeleij.demon.nl','','A032','Dames A-32','ADames','10','03',true,'A_A-32','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (22,'A035','Marina Tap-Hauer','Vrouw','fhtap@xs4all.nl','','A035','Dames A-35','ADames','11','03',true,'A_A-35','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (23,'A036','Shanti Haazer','Vrouw','haazer@zonnet.nl','','A036','Dames A-36','ADames','01','04',true,'A_A-36','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (24,'A038','Ineke van der Heide','Vrouw','Gbvanderheide@hetnet.nl','','A038','Dames A-38','ADames','04','04',true,'A_A-38','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (25,'A041','Lieske de Nooij','Vrouw','linooij@gmail.com','','A041','Dames A-41','ADames','05','04',true,'A_A-41','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (26,'A042','leeg','x','x','','A042','Dames A-42','ADames','06','04',false,'A_A-42','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (27,'A043','Diana de Rijk','Vrouw','derijkdiana@gmail.com','','A043','Dames A-43','ADames','07','04',true,'A_A-43','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (28,'A044','Ria Gorsira-de Voogd','Vrouw','h.r.geusebroek@gmail.com','','A044','Dames A-44','ADames','08','04',true,'A_A-44','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (29,'A045','Marian van Leeuwen-Scheltema','Vrouw','marianscheltema@gmail.com','','A045','Dames A-45','ADames','09','04',true,'A_A-45','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (30,'A046','leeg','x','x','','A046','Dames A-46','ADames','11','04',false,'A_A-46','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (31,'A048','Anneke Kuhurima','Vrouw','anjotona@hotmail.com','','A048','Dames A-48','ADames','12','02',true,'A_A-48','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (32,'B025','Nieske Heerema','Vrouw','nc.heerema@gmail.com','','B025','Dames B-25','BDames','01','03',true,'B_B-25','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (33,'B026','Janneke Nap','Vrouw','nap.janneke@gmail.com','','B026','Dames B-26','BDames','02','03',true,'B_B-26','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (34,'B027','Gerda Kwantes-Taams','Vrouw','gerdakwantes@gmail.com','','B027','Dames B-27','BDames','03','03',true,'B_B-27','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (35,'B028','Carolien Appeldoorn-de Lange','Vrouw','carappeldoorn@ziggo.nl','','B028','Dames B-28','BDames','04','03',true,'B_B-28','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (36,'B029','Carolina Scheepstra','Vrouw','carolina.scheepstra@inholland.nl','','B029','Dames B-29','BDames','05','03',true,'B_B-29','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (37,'B030','Bente Scheffer','Vrouw','bente.scheffer@xs4all.nl','','B030','Dames B-30','BDames','06','03',true,'B_B-30','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (38,'B031','Katja Moison','Vrouw','catharina.moison@gmail.com','','B031','Dames B-31','BDames','07','03',true,'B_B-31','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (39,'B032','leeg','x','x','','B032','Dames B-32','BDames','08','03',false,'B_B-32','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (40,'B033','Ellis Baaijen','Vrouw','baaijen@ziggo.nl','','B033','Dames B-33','BDames','09','03',true,'B_B-33','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (41,'B034','Elfi de Jong','Vrouw','elluf@hotmail.com','','B034','Dames B-34','BDames','10','03',true,'B_B-34','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (42,'B035','Leny Smit','Vrouw','LSmit1@Xs4all.nl','','B035','Dames B-35','BDames','01','04',true,'B_B-35','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (43,'B038','Marijke van Kuilenburg-le Maitre','Vrouw','maryke@casema.nl','','B038','Dames B-38','BDames','02','04',true,'B_B-38','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (44,'B039','Ieke Schiferli','Vrouw','iekeschiferli27@gmail.com','','B039','Dames B-39','BDames','03','04',true,'B_B-39','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (45,'B040','Paulien Lasterie','Vrouw','paulienlasterie@gmail.com','','B040','Dames B-40','BDames','04','04',true,'B_B-40','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (46,'B041','Jeannette de Groot','Vrouw','jce.groot@casema.nl','','B041','Dames B-41','BDames','07','04',true,'B_B-41','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (47,'B044','Marjolein Schepel','Vrouw','marjolein@schepeladvies.nl','','B044','Dames B-44','BDames','08','04',true,'B_B-44','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (48,'B045','Coco Wessel','Vrouw','corien@dapnijkerk.nl','','B045','Dames B-45','BDames','02','05',true,'B_B-45','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (49,'C051','Mira van der Mije','Vrouw','mail2mira@yahoo.com','','C051','Dames C-51','CDames','05','05',true,'C_C-51','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (50,'C054','Inge Haas','Vrouw','smorgens2@gmail.com','','C054','Dames C-54','CDames','08','05',true,'C_C-54','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (51,'H064','Kluisjesbeheer','Vrouw','ingeloes@gmail.com','','H048','CDames c-56','----','----','----',false,'label','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (52,'C057','Wilma Hanskamp','Vrouw','wilmahanskamp@hotmail.com','','C057','Dames C-57','CDames','10','05',true,'C_C-57','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (53,'C059','Teau de Vos van Steenwijk','Vrouw','teaudevosvansteenwijk@gmail.com','','C059','CDames C-59','CDames','12','05',true,'C_C-59','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (54,'C061','Manon Burger','Vrouw','manonburger1@gmail.com','','C061','Dames C-61','CDames','01','06',true,'C_C-61','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (55,'C062','Leonie van Bommel','Vrouw','leonievb1@gmail.com','','C062','Dames C-62','CDames','03','06',true,'C_C-62','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (56,'C064','Petra Gerritsen','Vrouw','petra.gerritsen@spletters.nl','','C064','Dames C-64','CDames','04','06',true,'C_C-64','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (57,'C065','Meta Rijks','Vrouw','mhrijks@planet.nl','','C065','Dames C-65','CDames','07','06',true,'C_C-65','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (58,'C068','Gerda Kruithof','Vrouw','gerdakruithof@icloud.com','','C068','Dames C-68','CDames','08','06',true,'C_C-68','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (59,'C069','Ellen van Dun','Vrouw','ellenvandun@casema.nl','','C069','Dames C-69','CDames','09','06',true,'C_C-69','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (60,'C070','Henny Sinnema','Vrouw','hl.sinlan@t-mobilethuis.nl','','C070','Dames C-70','CDames','10','06',true,'C_C-70','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (61,'C071','Ank Meyer','Vrouw','ankmeyer@xs4all.nl','','C071','Dames C-71','CDames','12','08',true,'C_C-71','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (62,'H001','Rik Vos','Man','rikderoodevos@kpnmail.nl','','H001','Heren 01','Heren','01','01',true,'H_01','H');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (63,'H002','Willie Ambergen','Man','willie@ambeleij.demon.nl','','H002','Heren 02','Heren','02','01',true,'H_02','H');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (64,'H003','Leo van den Broek','Man','leovandenbroek@casema.nl','','H003','Heren 03','Heren','03','01',true,'H_03','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (65,'H004','Cor Scheffers','Man','cor@corscheffers.nl','','H004','Heren 04','Heren','04','01',true,'H_04','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (66,'H005','leeg','x','x','','H005','Heren 05','Heren','05','01',false,'H_05','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (67,'H006','Edwin Foppen','Man','edwin.foppen@gmail.com','','H006','Heren 06','Heren','06','01',true,'H_06','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (68,'H007','Hans van Wijk','Man','joh.vanwijk@ziggo.nl','','H007','Heren 07','Heren','07','01',true,'H_07','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (69,'H008','Sjoerd Hagedoorn','Man','sjoerdhagedoorn@gmail.com','','H008','Heren 08','Heren','08','01',true,'H_08','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (70,'H009','leeg','Man','','','H009','Heren 09','Heren','09','01',true,'H_09','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (71,'H010','Wim Gorissen','Man','whmgorissen@gmail.com','','H010','Heren 10','Heren','10','01',true,'H_10','L');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (72,'H011','Tijmen van Gulik','Man','tijmen@vangulik.org','','H011','Heren 11','Heren','11','01',true,'H_11','H');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (73,'H012','Jean-François Raysz','Man','rayszjf@hotmail.com','','H012','Heren 12','Heren','12','01',true,'H_12','H');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (74,'H013','Hugo Linnenbank','Man','hugo@linnenbank.org','','H013','Heren 13','Heren','01','02',true,'H_13','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (75,'H014','Jeroen Bollen','Man','roeien@jeroenbollen.nl','','H014','Heren 14','Heren','03','02',true,'H_14','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (76,'H016','Peter Prak','Man','peter.prak@me.com','','H016','Heren 16','Heren','06','02',true,'H_16','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (77,'H019','Eric Bak','Man','ecr.bak@online.nl','','H019','Heren 19','Heren','07','02',true,'H_19','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (78,'H020','Theo Brok','Man','Tamerlan@xs4all.nl','','H020','Heren 20','Heren','08','02',true,'H_20','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (79,'H021','Jurjen Kolmer','Man','jurjen@kolmerweb.nl','','H021','Heren 21','Heren','09','02',true,'H_21','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (80,'H022','Peter Hingstman','Man','p.hingstman@hccnet.nl','','H022','Heren 22','Heren','10','02',true,'H_22','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (81,'H023','Theo Visser','Man','thmm.visser@ziggo.nl','','H023','Heren 23','Heren','11','02',true,'H_23','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (82,'H024','Gertjan Miedema','Man','gertjan@miedemageluid.nl','','H024','Heren 24','Heren','12','02',true,'H_24','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (83,'H025','Laurens van der Duijs','Man','laurensd007@gmail.com','','H025','Heren 25','Heren','01','03',true,'H_25','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (84,'H026','Martin Reniers','Man','martinreniers@hotmail.com','','H026','Heren 26','Heren','02','03',true,'H_26','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (85,'H027','Pieter Kwantes','Man','p.kwantes@ziggo.nl','','H027','Heren 27','Heren','04','03',true,'H_27','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (86,'H029','Gerard Ranke','Man','gerard.ranke@ziggo.nl','','H029','Heren 29','Heren','05','03',true,'H_29','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (87,'H030','Peter-Jan Tuk','Man','goldtuk@telfort.nl','','H030','Heren 30','Heren','07','03',true,'H_30','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (88,'H032','Jan Karel Tombrock','Man','JTombrock@ziggo.nl','','H032','Heren 32','Heren','08','03',true,'H_32','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (89,'H033','Dick Baars','Man','dickbaars@kpnplanet.nl','','H033','Heren 33','Heren','10','03',true,'H_33','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (90,'H035','Joan Schmidt','Man','joannemieke@kpnmail.nl','','H035','Heren 35','Heren','12','03',true,'H_35','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (91,'H037','Jeroen Paco Heydendael','Man','paco@redleafs.nl','','H037','Heren 37','Heren','01','04',true,'H_37','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (92,'H038','Marcel Linssen','Man','linssentandarts@gmail.com','','H038','Heren 38','Heren','02','04',true,'H_38','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (93,'H039','Henk Jan Kiewiet','Man','H.j.kiewiet@hccnet.nl','','H039','Heren 39','Heren','03','04',true,'H_39','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (94,'H040','Wim van de Bosch','Man','w.vandenbosch@planet.nl','','H040','Heren 40','Heren','04','04',true,'H_40','H');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (95,'H041','Peter Knappstein','Man','peterknappstein@seilemaaker.nl','','H041','Heren 41','Heren','05','04',true,'H_41','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (96,'H042','Erik van der Struijs','Man','erikvanderstruijs@xs4all.nl','','H042','Heren 42','Heren','06','04',true,'H_42','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (97,'H043','Bert Appeldoorn','Man','bertappeldoorn@ziggo.nl','','H043','Heren 43','Heren','07','04',true,'H_43','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (98,'H044','Stevin-Jan van Duijn','Man','sjduijn@yahoo.com','','H044','Heren 44','Heren','08','04',true,'H_44','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (99,'H045','Harold Thijssen','Man','Haroldthijssen@hetnet.nl','','H045','Heren 45','Heren','10','04',true,'H_45','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (100,'H047','Simon Glazenborg','Man','simon.glazenborg@gmail.com','','H047','Heren 47','Heren','11','04',true,'H_47','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (101,'H048','Tomas Klos','Man','tomasklos@gmail.com','','H048','Heren 48','Heren','02','05',true,'H_48','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (102,'H051','Hilco Bekenkamp','Man','hbekenkamp-viking@casema.nl','','H051','Heren 51','Heren','03','05',true,'H_51','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (103,'H052','Wim de Groot','Man','whdgroot@gmail.com','','H052','Heren 52','Heren','04','05',true,'H_52','H');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (104,'H053','Kees Wierenga','Man','c.wierenga@ziggo.nl','','H053','Heren 53','Heren','06','05',true,'H_53','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (105,'H055','André van Dort','Man','avdort@gmail.com','','H055','Heren 55','Heren','07','05',true,'H_55','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (106,'H056','Carel Reuser','Man','cmreuser@yahoo.com','','H056','Heren 56','Heren','08','05',true,'H_56','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (107,'H057','Edwin Ongkosuwito','Man','eongko@yahoo.com','','H057','Heren 57','Heren','09','05',true,'H_57','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (108,'H058','Peter Kerkhoven','Man','peter.m.kerkhoven@gmail.com','','H058','Heren 58','Heren','10','05',true,'H_58','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (109,'H059','Wessel Goossens','Man','wessel.goossens@gmail.com','','H059','Heren 59','Heren','12','05',true,'H_59','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (110,'H061','Frannie van Essen','Man','essen-van@ziggo.nl','','H061','Heren 61','Heren','02','06',true,'H_61','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (111,'H063','Martin Noorbergen','Man','martinwileenbiertje@hotmail.com','','H063','Heren 63','Heren','04','06',true,'H_63','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (112,'H064','Bert van Manen','Man','info@vanmanen.biz','','A008','Heren 64','Heren','----','----',true,'H_64','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (113,'H065','Gerard van Bruggen','Man','gerardvanbruggen64@hetnet.nl','','H065','Heren 65','Heren','06','06',true,'H_65','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (114,'H067','Robert ten Voorde','Man','rtenvoorde@datelvision.nl','','H067','Heren 67','Heren','08','06',true,'H_67','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (115,'H069','Dick Busscher','Man','die123@casema.nl','','H069','Heren 69','Heren','09','06',true,'H_69','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (116,'H070','Gerard Langeveld','Man','gelangeveld@gmail.com','','H070','Heren 70','Heren','12','02',true,'H_70','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (117,'H071','LEEG','Man','---','','H071','---','Heren','07','02',false,'label','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (118,'H072','wie heeft deze','Man','---','','H072','---','Heren','07','02',false,'label','--');
INSERT INTO "base_kluisjesrv" ("id","kluisnummer","naamvoluit","gender","email","userid","kluisje","kastje","topic","col","row","verhuurd","label","type") VALUES (119,'','wachtlijst','','','','','kast1','----','----','----',false,'label','--');
COMMIT;
