# Generated by Django 4.1 on 2022-10-28 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataimport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regel', models.TextField(default='-', max_length=540)),
            ],
        ),
        migrations.CreateModel(
            name='Flexevent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_text', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date', models.CharField(max_length=35)),
                ('datum', models.DateField()),
                ('pub_time', models.CharField(default='10:00', max_length=35)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lid', models.ManyToManyField(blank=True, related_name='deelnemer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flexrecurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regels', models.CharField(default='30', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viking.topic')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('email', models.CharField(blank=True, max_length=100)),
                ('is_flex', models.BooleanField(default=True)),
                ('is_host', models.BooleanField(default=False)),
                ('roeileeftijd', models.CharField(blank=True, max_length=20)),
                ('is_lid', models.BooleanField(default=True)),
                ('in_poule', models.BooleanField(default=False)),
                ('vaart', models.BooleanField(default=False)),
                ('pos1', models.CharField(choices=[('--', '--'), ('sc1', 'sc1'), ('sc2', 'sc2'), ('sc2a', 'sc2a'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('st1', 'st1'), ('st2', 'st2'), ('st3', 'st3')], default='sc1', max_length=18)),
                ('pos2', models.CharField(choices=[('--', '--'), ('sc1', 'sc1'), ('sc2', 'sc2'), ('sc2a', 'sc2a'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('st1', 'st1'), ('st2', 'st2'), ('st3', 'st3')], default='sc1', max_length=18)),
                ('pos3', models.CharField(choices=[('--', '--'), ('sc1', 'sc1'), ('sc2', 'sc2'), ('sc2a', 'sc2a'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('st1', 'st1'), ('st2', 'st2'), ('st3', 'st3')], default='sc1', max_length=18)),
                ('pos4', models.CharField(choices=[('--', '--'), ('sc1', 'sc1'), ('sc2', 'sc2'), ('sc2a', 'sc2a'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('st1', 'st1'), ('st2', 'st2'), ('st3', 'st3')], default='sc1', max_length=18)),
                ('pos5', models.CharField(choices=[('--', '--'), ('sc1', 'sc1'), ('sc2', 'sc2'), ('sc2a', 'sc2a'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('st1', 'st1'), ('st2', 'st2'), ('st3', 'st3')], default='st1', max_length=318)),
                ('coach', models.CharField(choices=[('--', '--'), ('sc1', 'sc1'), ('sc2', 'sc2'), ('sc2a', 'sc2a'), ('sc3', 'sc3'), ('sc4', 'sc4'), ('b1', 'b1'), ('b2', 'b2'), ('b3', 'b3'), ('b4', 'b4'), ('st1', 'st1'), ('st2', 'st2'), ('st3', 'st3')], default='st1', max_length=18)),
                ('keuzes', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viking.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Flexlid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('flexevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='viking.flexevent')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('member',),
            },
        ),
        migrations.AddField(
            model_name='flexevent',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viking.topic'),
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viking.flexevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
