# Generated by Django 4.1 on 2023-05-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instromer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='---', max_length=222)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='Kluislabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matriks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(default='matriks', max_length=18)),
                ('ronde', models.CharField(max_length=200)),
                ('kop', models.CharField(max_length=200)),
                ('regel', models.CharField(max_length=200)),
                ('x_as', models.IntegerField(default=2)),
                ('y_as', models.IntegerField(default=2)),
                ('kol1', models.CharField(default='000', max_length=18)),
                ('kol2', models.CharField(default='000', max_length=18)),
                ('kol3', models.CharField(default='000', max_length=18)),
                ('kol4', models.CharField(default='000', max_length=18)),
                ('kol5', models.CharField(default='000', max_length=18)),
                ('kol6', models.CharField(default='000', max_length=18)),
                ('kol7', models.CharField(default='000', max_length=18)),
                ('kol8', models.CharField(default='000', max_length=18)),
                ('kol9', models.CharField(default='000', max_length=18)),
                ('kol10', models.CharField(default='000', max_length=18)),
                ('kol11', models.CharField(default='000', max_length=18)),
                ('kol12', models.CharField(default='000', max_length=18)),
                ('kol13', models.CharField(default='000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vikinglid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('email', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='KluisjesRV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kluisnummer', models.CharField(max_length=200)),
                ('naamvoluit', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('userid', models.CharField(max_length=200)),
                ('kluisje', models.CharField(max_length=200)),
                ('kastje', models.CharField(default='kast1', max_length=18)),
                ('label', models.CharField(default='label', max_length=18)),
                ('type', models.CharField(choices=[('--', '--'), ('H', 'hang'), ('C', 'cijfer')], default='--', max_length=18)),
                ('topic', models.CharField(default='----', max_length=18)),
                ('row', models.CharField(default='----', max_length=18)),
                ('col', models.CharField(default='----', max_length=18)),
                ('verhuurd', models.BooleanField(default=False)),
                ('huurders', models.ManyToManyField(blank=True, related_name='huurders', to='viking.vikinglid')),
            ],
            options={
                'ordering': ['kluisnummer'],
            },
        ),
    ]
