# Generated by Django 4.1 on 2022-11-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0002_alter_room_options_kluis'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluis',
            name='name',
            field=models.CharField(default='-', max_length=200),
            preserve_default=False,
        ),
    ]
