# Generated by Django 4.1 on 2022-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0003_kluis_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluis',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
