# Generated by Django 4.1 on 2022-11-04 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viking', '0004_kluis_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluis',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
