# Generated by Django 4.1 on 2022-11-04 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viking', '0005_kluis_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kluis',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
    ]
