# Generated by Django 4.1 on 2022-11-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0007_remove_kluis_owner_kluis_owners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instromer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
