# Generated by Django 4.1 on 2022-11-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0009_kluis_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dataimport',
        ),
        migrations.AddField(
            model_name='kluis',
            name='sleutels',
            field=models.IntegerField(default=2),
        ),
    ]
