# Generated by Django 4.1 on 2022-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0010_delete_dataimport_kluis_sleutels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kluis',
            name='slot',
            field=models.CharField(choices=[('--', '--'), ('H', 'hang'), ('C', 'cijfer'), ('E', 'eigen'), ('V', 'Viking(hang)')], default='H', max_length=18),
        ),
    ]
