# Generated by Django 4.1 on 2022-11-23 19:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viking', '0012_kluis_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('datum', models.DateField()),
                ('pub_time', models.CharField(default='10:00', max_length=35)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lid', models.ManyToManyField(blank=True, related_name='taak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
