# Generated by Django 4.1 on 2022-11-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0013_rooster'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooster',
            name='lnr',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rooster',
            name='rnr',
            field=models.IntegerField(default=0),
        ),
    ]
