# Generated by Django 4.1 on 2022-12-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0014_rooster_lnr_rooster_rnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='lnr',
            field=models.IntegerField(default=0),
        ),
    ]
