# Generated by Django 4.1 on 2023-01-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0018_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='info',
            field=models.CharField(default='===', max_length=35),
        ),
    ]
