# Generated by Django 4.1 on 2023-02-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0018_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activiteit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('--', '--'), ('kluis', 'kluis'), ('ploeg', 'ploeg')], default='--', max_length=18)),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='person',
            name='in_poule',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_flex',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_host',
        ),
        migrations.RemoveField(
            model_name='person',
            name='lnr',
        ),
        migrations.RemoveField(
            model_name='person',
            name='roeileeftijd',
        ),
        migrations.RemoveField(
            model_name='person',
            name='vaart',
        ),
        migrations.CreateModel(
            name='Vikinglid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('avatar', models.ImageField(default='avatar.svg', null=True, upload_to='')),
                ('email', models.CharField(blank=True, max_length=100)),
                ('is_lid_van', models.ManyToManyField(blank=True, related_name='lid_van', to='viking.activiteit')),
            ],
        ),
    ]
