# Generated by Django 4.1 on 2023-01-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0019_note_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='owner',
            field=models.CharField(default='___', max_length=35),
        ),
    ]
