# Generated by Django 4.1 on 2023-01-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0020_note_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='info',
        ),
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
    ]
