# Generated by Django 4.1 on 2023-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0021_remove_note_info_remove_note_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='info',
            field=models.CharField(default='===', max_length=35),
        ),
    ]
