# Generated by Django 4.1 on 2023-01-21 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0022_note_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='info',
        ),
    ]
