# Generated by Django 4.1 on 2023-02-05 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0019_activiteit_remove_person_coach_and_more'),
        ('viking', '0023_remove_note_info'),
    ]

    operations = [
    ]
