# Generated by Django 4.1 on 2023-02-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0024_merge_20230205_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='vikinglid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 10, 16, 10, 1, 111354, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vikinglid',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
