# Generated by Django 4.1 on 2023-02-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0025_vikinglid_created_vikinglid_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vikinglid',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
