# Generated by Django 4.1 on 2023-03-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0026_alter_vikinglid_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='vikinglid',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
