# Generated by Django 4.1 on 2023-03-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0027_vikinglid_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kluis',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
