# Generated by Django 4.1 on 2023-03-06 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0028_alter_kluis_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kluis',
            name='topic',
        ),
    ]
