# Generated by Django 4.1 on 2023-03-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0029_remove_kluis_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluis',
            name='topic',
            field=models.CharField(default='XXX', max_length=18),
        ),
    ]
