# Generated by Django 4.1 on 2023-03-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0030_kluis_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kluis',
            name='owners',
        ),
    ]
