# Generated by Django 4.1 on 2023-03-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0031_remove_kluis_owners'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instromer',
        ),
    ]
