# Generated by Django 4.1 on 2023-03-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0032_delete_instromer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flexrecurrent',
        ),
    ]
