# Generated by Django 4.1 on 2023-03-06 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0033_delete_flexrecurrent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooster',
        ),
    ]
