# Generated by Django 4.1 on 2023-03-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0034_delete_rooster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kluis',
            old_name='user',
            new_name='user_id',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
