# Generated by Django 4.1 on 2023-03-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0035_rename_user_kluis_user_id_delete_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kluis',
            old_name='topic',
            new_name='topic_id',
        ),
        migrations.AlterField(
            model_name='kluis',
            name='slot',
            field=models.CharField(default='H', max_length=18),
        ),
    ]
