# Generated by Django 4.1 on 2023-03-06 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0036_rename_topic_kluis_topic_id_alter_kluis_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kluis',
            name='topic_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
