# Generated by Django 4.1 on 2023-03-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0037_alter_kluis_topic_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.AlterModelOptions(
            name='vikinglid',
            options={'ordering': ['name', '-updated']},
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
