# Generated by Django 4.1 on 2023-04-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0038_remove_room_host_remove_room_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronde', models.CharField(max_length=200)),
                ('kop', models.CharField(max_length=200)),
                ('regel', models.CharField(max_length=200)),
            ],
        ),
    ]
