# Generated by Django 4.1 on 2023-04-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0039_matriks'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriks',
            name='x_as',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='matriks',
            name='y_as',
            field=models.IntegerField(default=2),
        ),
    ]
