# Generated by Django 4.1 on 2023-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0040_matriks_x_as_matriks_y_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluis',
            name='kast',
            field=models.CharField(default='kast1', max_length=18),
        ),
    ]
