# Generated by Django 4.1 on 2023-04-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0041_kluis_kast'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriks',
            name='kol1',
            field=models.CharField(default='kast1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol2',
            field=models.CharField(default='kast1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol3',
            field=models.CharField(default='kast1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol4',
            field=models.CharField(default='kast1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol5',
            field=models.CharField(default='kast1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol6',
            field=models.CharField(default='kast1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol7',
            field=models.CharField(default='kast1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol8',
            field=models.CharField(default='kast1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol9',
            field=models.CharField(default='kast1', max_length=18),
        ),
    ]
