# Generated by Django 4.1 on 2023-04-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0042_matriks_kol1_matriks_kol2_matriks_kol3_matriks_kol4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriks',
            name='kol10',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol11',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol12',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AddField(
            model_name='matriks',
            name='kol13',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol1',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol2',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol3',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol4',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol5',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol6',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol7',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol8',
            field=models.CharField(default='1', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol9',
            field=models.CharField(default='1', max_length=18),
        ),
    ]
