# Generated by Django 4.1 on 2023-04-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0043_matriks_kol10_matriks_kol11_matriks_kol12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriks',
            name='naam',
            field=models.CharField(default='matriks', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol1',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol10',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol11',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol12',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol13',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol2',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol3',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol4',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol5',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol6',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol7',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol8',
            field=models.CharField(default='000', max_length=18),
        ),
        migrations.AlterField(
            model_name='matriks',
            name='kol9',
            field=models.CharField(default='000', max_length=18),
        ),
    ]
