# Generated by Django 4.1 on 2023-04-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0044_matriks_naam_alter_matriks_kol1_alter_matriks_kol10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KluisjesRV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kluisnummer', models.TextField()),
                ('naamvoluit', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('slot', models.CharField(default='H', max_length=18)),
                ('email', models.IntegerField(default=2)),
                ('userid', models.CharField(max_length=200)),
                ('kluisje', models.CharField(max_length=200)),
                ('kastje', models.CharField(default='kast1', max_length=18)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
