# Generated by Django 4.1 on 2023-04-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0046_alter_kluisjesrv_options_remove_kluisjesrv_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kluisjesrv',
            name='slot',
        ),
    ]
