# Generated by Django 4.1 on 2023-04-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0048_alter_kluisjesrv_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kluisjesrv',
            name='kluisnummer',
            field=models.CharField(max_length=200),
        ),
    ]
