# Generated by Django 4.1 on 2023-04-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0049_alter_kluisjesrv_kluisnummer'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluisjesrv',
            name='topic',
            field=models.CharField(default='----', max_length=18),
        ),
    ]
