# Generated by Django 4.1 on 2023-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0050_kluisjesrv_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluisjesrv',
            name='col',
            field=models.CharField(default='----', max_length=18),
        ),
        migrations.AddField(
            model_name='kluisjesrv',
            name='row',
            field=models.CharField(default='----', max_length=18),
        ),
        migrations.AddField(
            model_name='kluisjesrv',
            name='verhuurd',
            field=models.BooleanField(default=False),
        ),
    ]
