# Generated by Django 4.1 on 2023-04-26 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0051_kluisjesrv_col_kluisjesrv_row_kluisjesrv_verhuurd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kluis',
        ),
    ]
