# Generated by Django 4.1 on 2023-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0052_delete_kluis'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluisjesrv',
            name='huurder',
            field=models.ManyToManyField(blank=True, related_name='huurders', to='viking.matriks'),
        ),
    ]
