# Generated by Django 4.1 on 2023-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0053_kluisjesrv_huurder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kluisjesrv',
            name='huurder',
        ),
        migrations.AddField(
            model_name='kluisjesrv',
            name='huurders',
            field=models.ManyToManyField(blank=True, related_name='huurders', to='viking.vikinglid'),
        ),
    ]
