# Generated by Django 4.1 on 2023-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0054_remove_kluisjesrv_huurder_kluisjesrv_huurders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriks90',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(default='matriks', max_length=18)),
                ('ronde', models.CharField(max_length=200)),
                ('kop', models.CharField(max_length=200)),
                ('regel', models.CharField(max_length=200)),
                ('x_as', models.IntegerField(default=2)),
                ('y_as', models.IntegerField(default=2)),
                ('kol1', models.CharField(default='000', max_length=18)),
                ('kol2', models.CharField(default='000', max_length=18)),
                ('kol3', models.CharField(default='000', max_length=18)),
                ('kol4', models.CharField(default='000', max_length=18)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kluisjesrv',
            options={'ordering': ['kluisnummer']},
        ),
    ]
