# Generated by Django 4.1 on 2023-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0055_matriks90_alter_kluisjesrv_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kluislabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
