# Generated by Django 4.1 on 2023-05-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0057_kluisjesrv_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluisjesrv',
            name='type',
            field=models.CharField(choices=[('--', '--'), ('H', 'hang'), ('C', 'cijfer')], default='--', max_length=18),
        ),
    ]
