# Generated by Django 4.1 on 2023-05-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0058_kluisjesrv_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matriks90',
        ),
    ]
