# Generated by Django 4.1 on 2023-05-06 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viking', '0059_delete_matriks90'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vikinglid',
            name='is_lid_van',
        ),
        migrations.DeleteModel(
            name='Activiteit',
        ),
    ]
