BEGIN TRANSACTION;
DROP TABLE IF EXISTS "viking_activiteit";
CREATE TABLE IF NOT EXISTS "viking_activiteit" (
	"id"	integer NOT NULL,
	"name"	varchar(100) NOT NULL,
	"type"	varchar(18) NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (1,'Dames 04','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (2,'Dames 14','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (3,'Dames 20','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (4,'Dames A-25','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (5,'Dames A-26','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (6,'Dames A-27','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (7,'Dames A-32','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (8,'Dames A-36','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (9,'Dames A-41','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (10,'Dames A-44','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (11,'Dames A-45','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (12,'Dames A-48','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (13,'Dames B-25','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (14,'Dames B-26','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (15,'Dames B-28','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (16,'Dames B-33','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (17,'Dames B-40','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (18,'Dames B-44','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (19,'Dames B-45','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (20,'Dames C-51','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (21,'Dames C-65','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (22,'Heren 01','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (23,'Heren 02','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (24,'Heren 03','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (25,'Heren 04','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (26,'Heren 08','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (27,'Heren 10','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (28,'Heren 14','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (29,'Heren 23','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (30,'Heren 24','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (31,'Heren 27','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (32,'Heren 30','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (33,'Heren 33','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (34,'Heren 37','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (35,'Heren 40','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (36,'Heren 42','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (37,'Heren 43','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (38,'Heren 44','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (39,'Heren 45','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (40,'Heren 47','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (41,'Heren 53','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (42,'Heren 55','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (43,'Heren 56','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (44,'Heren 64','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (45,'Heren 69','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (46,'Dames 01','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (47,'Dames 05','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (48,'Dames 07','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (49,'Dames 08','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (50,'Dames 09','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (51,'Dames 12','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (52,'Dames 13','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (53,'Dames 15','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (54,'Dames 16','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (55,'Dames 19','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (56,'Dames 21','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (57,'Dames 23','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (58,'Dames 24','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (59,'Dames A-31','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (60,'Dames A-35','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (61,'Dames A-38','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (62,'Dames A-42','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (63,'Dames A-43','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (64,'Dames A-46','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (65,'Dames B-27','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (66,'Dames B-29','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (67,'Dames B-30','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (68,'Dames B-31','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (69,'Dames B-32','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (70,'Dames B-34','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (71,'Dames B-35','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (72,'Dames B-38','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (73,'Dames B-39','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (74,'Dames B-41','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (75,'Dames C-54','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (76,'Dames c-56','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (77,'Dames C-57','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (78,'Dames C-59','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (79,'Dames C-61','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (80,'Dames C-62','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (81,'Dames C-64','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (82,'Dames C-68','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (83,'Dames C-69','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (84,'Dames C-70','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (85,'Dames C-71','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (86,'Heren 05','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (87,'Heren 06','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (88,'Heren 07','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (89,'Heren 09','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (90,'Heren 11','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (91,'Heren 12','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (92,'Heren 13','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (93,'Heren 16','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (94,'Heren 19','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (95,'Heren 20','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (96,'Heren 21','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (97,'Heren 22','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (98,'Heren 25','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (99,'Heren 26','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (100,'Heren 29','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (101,'Heren 32','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (102,'Heren 35','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (103,'Heren 38','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (104,'Heren 39','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (105,'Heren 41','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (106,'Heren 48','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (107,'Heren 51','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (108,'Heren 52','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (109,'Heren 57','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (110,'Heren 58','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (111,'Heren 59','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (112,'Heren 61','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (113,'Heren 63','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (114,'Heren 65','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (115,'Heren 67','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (116,'Heren 70','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (117,'Wachtlijst','kluis');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (343,'4M&G','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (344,'Akoko Flamingo','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (345,'Barmuda','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (346,'Brute Brunettes','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (347,'CHOAS','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (348,'Catch Of The Day','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (349,'Catch of the Day','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (350,'De Walkuren','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (351,'De Walkures','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (352,'De groot','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (353,'De vroege vijf','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (354,'Early Birds','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (355,'F**ing Viking Top 8+','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (356,'Four in a row','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (357,'Glad4','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (358,'Guld Gädda','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (359,'Het U-team','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (360,'Instromers','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (361,'JA-WE-roeien','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (362,'Jong','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (363,'Kastjes Dames','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (364,'Kastjes Heren','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (365,'Lenny & Mira','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (366,'MerwedeMermaids','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (367,'Najaar 2019(1)','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (368,'Najaar 2019(2)','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (369,'Najaar 2019(3)','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (370,'Najaar 2019(4)','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (371,'Niet zonder slag of boot','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (372,'Op slag verliefd','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (373,'PL_dehaas','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (374,'PL_vanderzweep','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (375,'Pijn is Fijn 8x','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (376,'PijnisFijn','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (377,'Pl_Bronkhorst','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (378,'Pl_Stolker','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (379,'Ploeg Broekema','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (380,'Ploeg Bronkhorst','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (381,'Ploeg Custers','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (382,'Ploeg Eijsbroek','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (383,'Ploeg Lans','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (384,'Ploeg Mira','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (385,'Ploeg Schepel','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (386,'Ploeg Spronck','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (387,'Ploeg Wierenga','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (388,'ROAR','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (389,'Road to Tokyo','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (390,'Roar','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (391,'Rodare','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (392,'Roddare','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (393,'Roeien met Ambitie','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (394,'Roeio de Tokyo','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (395,'Roeiploeg','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (396,'RoeyVief','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (397,'Spider girls','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (398,'Stayokay','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (399,'Still Rowing Strong','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (400,'Team Boomstam','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (401,'Team Dennis','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (402,'Tuk','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (403,'V.U.C','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (404,'V75+/ oude herenacht','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (405,'VUC','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (406,'Veldkeuken','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (407,'Viking dames 27','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (408,'Voorjaar 2019(2)','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (409,'Vroege Vogels','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (410,'Wierenga','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (411,'Zondagmorgen 9.30 uur','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (412,'gladde alen','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (413,'huntjens','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (414,'pl_Kwantes','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (415,'pl_Zwaag','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (416,'pl_baas','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (417,'pl_lans','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (418,'pl_nagel','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (419,'plg Gil Rodriques','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (420,'ploeg Eijsbroek','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (421,'ploeg Kwantes','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (422,'ploeg Schepel','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (423,'ploeg Tuk','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (424,'ploeg van vilsteren - youngsters','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (425,'team broekema','ploeg');
INSERT INTO "viking_activiteit" ("id","name","type") VALUES (426,'vikingschuivers','ploeg');
COMMIT;
