from django.urls import path

from viking.views import( 
AanmeldView,
FlexeventsView,
ResultsView,
activiteit,
activityPage,
apiOverview, 
createRoom, deleteMessage, deleteRoom,
KluisPage,
erv_activityPage,
erv_createRoom,
erv_deleteMessage,
erv_deleteRoom,
PloegPage,
erv_loginPage,
erv_room,
erv_topicsPage,
erv_updateRoom,
erv_updateUser,
erv_userProfile,
events, 
home,
gebruikerslijst,
loginPage, logoutUser,
personenlijst,
recurrent_event,
registerPage, room, 
topicsPage, updateRoom, updateUser, userProfile,
vote, kluis,
DetailView,
aantalregels,
)

urlpatterns = [
    path('', home, name='home'),
    path('viking', home, name='home'),
    path('login/', loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('topics/', topicsPage, name="topics"),
    path('update-user/', updateUser, name="update-user"),
    path('register/', registerPage, name="register"),    
    path('profile/<str:pk>/', userProfile, name='user-profile'),
    path('create-room/', createRoom, name='create-room'),
    path('update-room/<str:pk>/', updateRoom, name='update-room'),
    path('delete-room/<str:pk>/', deleteRoom, name='delete-room'),
    path('delete-message/<str:pk>/', deleteMessage, name='delete-message'),
    path('activity/', activityPage, name="activity"),

    path('urv-create-flex/', erv_createRoom, name='urv-create-flex'),
    path('urv-update-flex/<str:pk>/', erv_updateRoom, name='urv-update-flex'),
    path('erv_activity/', erv_activityPage, name="urv-activity"),
    path('room/<str:pk>/', room, name='room'),    
    path('urv-topics/', erv_topicsPage, name="urv-topics"),
    path('urv-delete-room/<str:pk>/', erv_deleteRoom, name='urv-delete-room'),
    path('urv-profile/<str:pk>/', erv_userProfile, name='urv-user-profile'),
    path('urv-update-room/<str:pk>/', erv_updateRoom, name='urv-update-room'),
    path('urv-delete-message/<str:pk>/', erv_deleteMessage, name='urv-delete-message'),
    path('urv-login/', erv_loginPage, name="urv-login"),
    path('urv-logout/', logoutUser, name="urv-logout"),
    path('urv-register/', registerPage, name="urv-register"),    
    path('urv-update-user/', erv_updateUser, name="urv-update-user"),

    path('recurrent/', recurrent_event, name='recurrent'),
    path('<int:room_id>/aanmelden/',vote, name='vote'),  
    path('<int:kluis_id>/kluisjes/',kluis, name='kluis'),  
    path('ploegbeheer/',PloegPage , name="ploegbeheer"),
    path('kluisbeheer/',KluisPage , name="kluisbeheer"),
    path('<int:pk>/', DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', ResultsView.as_view(), name='results'),
    path('api/person/', personenlijst,name='api-person'),    
    path('api/gebruikers/', gebruikerslijst,name='api-gebruikers'),    
    path('api/', apiOverview,name='api-overview'),    
    path('api/aantalregels/', aantalregels,name='api-aantalregels'),    
    path('activiteit/<str:pk>/', activiteit,name='activiteit'),    
    ]
# https://docs.djangoproject.com/en/3.1/topics/http/urls/