from django.urls import path
from . import views
from viking.views import( 
home,
loginPage, logoutUser,
registerPage , 
topicsPage ,  updateUser, userProfile,
 urv_loginPage ,
 check_matriks,
createVikinglid,deleteVikinglid, 
aanvrage,export_team_data,Blokken,get_matrix,get_kluis,set_kluis,update_kluis
)
# DetailView,
# gebruikerslijst,
#  createRequest , 
# kluisje, 
# get_vikinglid,
# urv_updateKluis ,
# KluisPage , 
# activiteit,
# AanmeldView ,
#  activityPage ,
# getRoutes,
# add_activity,
urlpatterns = [
    path('', home, name='home'),
    path('viking', home, name='home'),
    path('login/', urv_loginPage, name="login"),
    path('logout/', logoutUser, name="logout"),
    path('topics/', topicsPage, name="topics"),
    path('update-user/', updateUser, name="update-user"),
    path('register/', registerPage, name="register"),    
    path('profile/<str:pk>/', userProfile, name='user-profile'),
    path('create-vikinglid/', createVikinglid, name='create-vikinglid'),
    path('create-aanvrage/', aanvrage, name='create-aanvrage'),
    path('delete-vikinglid/<str:pk>/', deleteVikinglid, name='delete-vikinglid'),
    path('export/', export_team_data, name='export'),
    path('notes/', views.getNotes, name="notes"),
    path('api/topics/', views.getTopics, name="topics"),
    path('notes/<str:pk>/', views.getNote, name="note"),
     path('blokken/<str:name>', Blokken.as_view(), name='blokken'),
    path('get_matrix/',get_matrix, name='get_matrix'),  
    path('<str:pk>/set_kluis/<str:kol>',set_kluis, name='set_kluis'),  
    path('<str:pk>/update_kluis/<str:kol>/',update_kluis, name='update_kluis'),  
    path('checkmatriks/', check_matriks, name='checkmatriks'),
    ]
    # path('<int:kluis_id>/kluisje/',kluisje, name='kluisje'),  
    # path('<int:pk>/', DetailView.as_view(), name='detail'),
    # path('vikinglid/', get_vikinglid, name='vikinglid'),
    # path('<str:pk>/update-kluis/',urv_updateKluis, name='update-kluis'),  
    # path('kluisbeheer/',KluisPage , name="kluisbeheer"),
    # path('add_activity/',add_activity, name='add_activity'),  # utility call
    # path('activiteit/<str:lid_id>',activiteit, name='activiteit'),  
    # path('<int:room_id>/aanmelden/',vote, name='vote'),  
    # path('activity/', activityPage, name="activity"),
    # path('activiteiten/', views.getActiviteiten, name="activiteiten"),
    # path('activiteiten/<str:pk>/', views.getActiviteit, name="activiteiten"),
    # path('notes/create/', views.createNote, name="create-note"),
    # path('notes/<str:pk>/update/', views.updateNote, name="update-note"),
    # path('notes/<str:pk>/delete/', views.deleteNote, name="delete-note"),
    # path('notes/<str:find>/find/', views.findNote, name="find-note"),
    # path('<str:pk>/get_kluis/<str:kol>/',get_kluis, name='get_kluis'),  
    # path('create-room/', createRoom, name='create-room'),
    # path('update-room/<str:pk>/', updateRoom, name='update-room'),
# https://docs.djangoproject.com/en/3.1/topics/http/urls/
# path('<int:id>/equipe_detail/<slug:slug>/', equipe_detailHL, name='equipe_detailHL'),