# Generated by Django 3.2.7 on 2024-03-23 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturatielijst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockerlabel', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('in_excel', models.CharField(default='----', max_length=200)),
                ('renum', models.CharField(max_length=200, null=True)),
                ('is_registered', models.CharField(default='----', max_length=200)),
                ('type', models.CharField(choices=[('--', '--'), ('H', 'hang'), ('C', 'cijfer')], default='--', max_length=18)),
                ('obsolete', models.BooleanField(default=False)),
                ('sleutels', models.CharField(default='----', max_length=18)),
                ('code', models.CharField(default='----', max_length=18)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Helptekst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('seq', models.CharField(default='----', max_length=18)),
                ('publish', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lockerlabel', models.CharField(max_length=200)),
                ('email', models.CharField(default='--', max_length=200)),
                ('nieuwe_huurder', models.CharField(default='--', max_length=200)),
                ('vorige_huurder', models.CharField(default='--', max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('--', '--'), ('H', 'hang'), ('C', 'cijfer')], default='--', max_length=18)),
                ('locker', models.CharField(default='----', max_length=18)),
                ('verhuurd', models.BooleanField(default=False)),
                ('opgezegd', models.BooleanField(default=False)),
                ('obsolete', models.BooleanField(default=False)),
                ('tekst', models.TextField(blank=True)),
                ('sleutels', models.CharField(default='----', max_length=18)),
                ('code', models.CharField(default='----', max_length=18)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('opzegdatum', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['lockerlabel'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('onderhuur', models.BooleanField(default=False)),
                ('kamer', models.CharField(choices=[('', '--------'), ('D', 'D'), ('H', 'H')], default='X', max_length=18)),
                ('wachtlijst', models.BooleanField(default=False)),
                ('hoofdhuurder', models.BooleanField(default=False)),
                ('locker', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('tekst', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Ploeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.locker')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.locker')),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
