# Generated by Django 4.1 on 2023-05-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kluisjesrv',
            name='userid',
        ),
    ]
