# Generated by Django 3.2.7 on 2024-03-24 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_areset_tijdregel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bericht',
            name='locker',
        ),
        migrations.AddField(
            model_name='bericht',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
