# Generated by Django 4.1 on 2023-06-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_lockers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lockers',
            new_name='Locker',
        ),
    ]
