# Generated by Django 4.1 on 2024-03-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20240324_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locker',
            options={'ordering': ['inspectie']},
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='lockerlabel',
            new_name='inspectie',
        ),
    ]
