# Generated by Django 4.1 on 2023-06-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_lockers_locker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KluisjesRV',
        ),
    ]
