# Generated by Django 4.1 on 2023-06-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_kluisjesrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='code',
            field=models.CharField(default='----', max_length=18),
        ),
        migrations.AddField(
            model_name='locker',
            name='sleutels',
            field=models.CharField(default='----', max_length=18),
        ),
    ]
