# Generated by Django 4.1 on 2023-07-02 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_locker_code_locker_sleutels'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ploeg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
