# Generated by Django 4.1 on 2023-07-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_ploeg'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locker',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
