# Generated by Django 4.1 on 2023-07-12 18:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_locker_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ploeg',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='teammembers', to=settings.AUTH_USER_MODEL),
        ),
    ]
