# Generated by Django 4.1 on 2023-07-29 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_ploeg_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='locker',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.locker'),
            preserve_default=False,
        ),
    ]
