# Generated by Django 4.1 on 2023-08-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_helptekst'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptekst',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='helptekst',
            name='seq',
            field=models.CharField(default='----', max_length=18),
        ),
    ]
