# Generated by Django 4.1 on 2023-09-02 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_bericht'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
