# Generated by Django 4.1 on 2023-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_excellijst'),
    ]

    operations = [
        migrations.AddField(
            model_name='excellijst',
            name='excel',
            field=models.CharField(default='----', max_length=200),
        ),
    ]
