# Generated by Django 4.1 on 2023-09-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='person',
            name='hoofdhuurder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='onderhuur',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='wachtlijst',
            field=models.BooleanField(default=False),
        ),
    ]
