# Generated by Django 4.1 on 2023-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_facturatielijst_delete_matriks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excellijst',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
