# Generated by Django 4.1 on 2023-09-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_excellijst_options_remove_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='col',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='row',
        ),
    ]
