# Generated by Django 4.1 on 2023-09-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_locker_col_remove_locker_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tekst',
            field=models.TextField(blank=True),
        ),
    ]
