# Generated by Django 4.1 on 2023-09-24 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_person_tekst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['email']},
        ),
    ]
