# Generated by Django 4.1 on 2023-09-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='base.person'),
        ),
    ]
