# Generated by Django 4.1 on 2023-10-04 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_locker_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
