# Generated by Django 4.1 on 2023-10-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_locker_obsolete'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturatielijst',
            name='renum',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
