# Generated by Django 4.1 on 2023-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_facturatielijst_renum'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturatielijst',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
