# Generated by Django 4.1 on 2023-10-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_person_created_person_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='opgezegd',
            field=models.BooleanField(default=False),
        ),
    ]
