# Generated by Django 4.1 on 2023-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_locker_opgezegd'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='tekst',
            field=models.TextField(blank=True),
        ),
    ]
