# Generated by Django 4.1 on 2023-10-07 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_locker_tekst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='locker',
            name='participants',
        ),
    ]
