# Generated by Django 4.1 on 2023-10-12 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_locker_owners_remove_locker_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='opzegdatum',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 12, 14, 25, 32, 889360)),
        ),
    ]
