# Generated by Django 4.1 on 2023-10-12 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_locker_opzegdatum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='opzegdatum',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 12, 14, 28, 41, 693159)),
        ),
    ]
