# Generated by Django 4.1 on 2023-10-12 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_locker_opzegdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='nieuwe_huurder',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='locker',
            name='email',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='locker',
            name='opzegdatum',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 12, 14, 30, 45, 882329)),
        ),
    ]
