# Generated by Django 4.1 on 2023-10-12 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_locker_nieuwe_huurder_alter_locker_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='vorige_huurder',
            field=models.CharField(default='--', max_length=200),
        ),
        migrations.AlterField(
            model_name='locker',
            name='opzegdatum',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 12, 15, 43, 16, 93950)),
        ),
    ]
