# Generated by Django 4.1 on 2023-10-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_locker_updated_locker_vorige_huurder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='opzegdatum',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
