# Generated by Django 4.1 on 2023-11-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_locker_opzegdatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='kamer',
            field=models.CharField(choices=[('', '--------'), ('D', 'D'), ('H', 'H')], default='X', max_length=18),
        ),
    ]
