# Generated by Django 4.1 on 2024-01-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_person_kamer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Areset',
        ),
    ]
