# Generated by Django 4.1 on 2024-01-18 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_rename_room_areset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tijdregel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='--', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('begin', models.DateTimeField(auto_now=True)),
                ('einde', models.DateTimeField(auto_now=True)),
                ('tijdregel', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.areset')),
            ],
            options={
                'ordering': ['tijdregel'],
            },
        ),
    ]
