# Generated by Django 4.1 on 2024-01-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_tijdregel'),
    ]

    operations = [
        migrations.AddField(
            model_name='areset',
            name='status',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
