# Generated by Django 4.1 on 2024-02-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_room_remove_areset_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='kluisje',
            new_name='label',
        ),
    ]
