# Generated by Django 4.1 on 2024-02-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participants',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
