# Generated by Django 4.1 on 2024-02-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_rename_kluisje_locker_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='topic',
            new_name='locker',
        ),
    ]
