# Generated by Django 4.1 on 2024-02-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_rename_topic_locker_locker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='locker',
            new_name='topic',
        ),
    ]
