# Generated by Django 4.1 on 2024-02-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_rename_locker_locker_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='locker',
            name='locker',
            field=models.CharField(default='----', max_length=18),
        ),
    ]
