# Generated by Django 4.1 on 2024-02-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_locker_locker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='locker',
        ),
    ]
