# Generated by Django 4.1 on 2024-02-24 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_remove_locker_locker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locker',
            old_name='topic',
            new_name='locker',
        ),
    ]
