# Generated by Django 4.1 on 2024-02-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_rename_topic_locker_locker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locker',
            options={'ordering': ['lockerlabel']},
        ),
        migrations.RenameField(
            model_name='excellijst',
            old_name='kluisnummer',
            new_name='lockerlabel',
        ),
        migrations.RenameField(
            model_name='facturatielijst',
            old_name='kluisnummer',
            new_name='lockerlabel',
        ),
        migrations.RenameField(
            model_name='locker',
            old_name='kluisnummer',
            new_name='lockerlabel',
        ),
    ]
