# Generated by Django 4.1 on 2024-03-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_alter_locker_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Excellijst',
        ),
    ]
