from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', views.home, name="home"),
    path('activity/', views.activityPage, name="activity"),
    path('info/', views.infoPage, name="info"),
    path('room/<str:pk>/', views.lockerPage, name="room"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('registreer/', views.CreateUser.as_view(), name="registreer"),
    path('update-user/', views.updateUser, name="update-user"),
    path('update-user2/<str:pk>', views.updateUser3.as_view(), name="update-user2"),
    path('update-person/<str:pk>', views.PersonUpdate_id.as_view(), name="update-person"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('profile/', views.myProfile, name="profile"),
    path('topics/', views.topicsPage, name="topics"),
    path('users/', views.MemberListView.as_view(), name="users"),
    path('profiles/',login_required(views.PersonListView.as_view()),name='profiles'),
    path('lockers/', views.LockerView.as_view(), name="lockers"),
    path('vrijelockers/', views.ExcelView.as_view(), name="vrijelockers"),
    path('excellijst/', views.ExcelView.as_view(), name="excellijst"),
    path('facturatielijst/', views.FacturatieView.as_view(), name="facturatielijst"),
    path('ploeg/<str:pk>', views.ploegPage, name="ploeg"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('create-room/', views.createRoom, name="create-room"),
    path('create-person/', views.CreatePerson.as_view(), name="create-person"),
    path('delete-person/<str:pk>',views.PersonDeleteView.as_view(),name='delete-person'),
    path('delete-locker/<str:pk>',views.LockerDeleteView.as_view(),name='delete-locker'),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),
    path('delete-bericht/<str:pk>/', views.deleteBericht, name="delete-bericht"),
    path('<str:pk>/locker/',views.lockerPage, name='locker'),  
    path('<str:pk>/excel-regel/',views.excel_regelPage, name='excel-regel'),  
    path('<str:pk>/update-locker/',views.LockerUpdate.as_view(), name='update-locker'),  
    path('<str:row>/create_locker/<str:kol>/',views.create_locker, name='create_locker'),  
    path('helptekst/', views.helpPage, name='helptekst'),
    path('berichten/', views.berichtenPage, name="berichten"),
     path('aantalregistraties/', views.tel_aantal_registraties, name='aantalregistraties'),
         # path('register/', views.registerPage, name="register"),
    # path('profiles/', views.PersonListView.as_view(), name="profiles"),
    # path('lockers/', login_required(views.LockerView.as_view()), name="lockers"),
   # path('users/', views.user_listPage, name="users"),
    # path('profiles/', views.profilePage, name="profiles"),
    # path('hernummermatriks/', views.hernummermatriks, name='hernummermatriks'),
    # path('locker-blokken/', views.Blokken.as_view(), name='locker-blokken'),
    # path('nietverhuurd/',views.nietverhuurdePage, name='nietverhuurd'),  
    ]
# https://docs.djangoproject.com/en/3.1/topics/http/urls/