from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('activity/', views.activityPage, name="activity"),
    path('help/', views.helpPage, name="help"),
    path('info/', views.infoPage, name="info"),
    path('room/<str:pk>/', views.lockerPage, name="room"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),
    path('update-user/', views.updateUser, name="update-user"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('topics/', views.topicsPage, name="topics"),
    path('ploegen/', views.ploegenPage, name="ploegen"),
    path('lockers/', views.lockersPage, name="lockers"),
    path('ploeg/<str:pk>', views.ploegPage, name="ploeg"),
    path('update-room/<str:pk>/', views.updateRoom, name="update-room"),
    path('delete-room/<str:pk>/', views.deleteRoom, name="delete-room"),
     path('create-room/', views.createRoom, name="create-room"),
    path('delete-message/<str:pk>/', views.deleteMessage, name="delete-message"),
    path('<str:pk>/kluis/',views.kluis, name='kluis'),  
    path('<str:pk>/locker/',views.lockerPage, name='locker'),  
    path('<str:pk>/update_kluis/<str:kol>/',views.update_kluis, name='update_kluis'),  
    path('<str:pk>/update_locker/',views.updateLocker, name='update_locker'),  
    path('<str:row>/create_locker/<str:kol>/',views.create_locker, name='create_locker'),  
    path('hernummermatriks/', views.hernummermatriks, name='hernummermatriks'),
    path('locker-blokken/', views.Blokken.as_view(), name='locker-blokken'),
    path('nietverhuurd/',views.nietverhuurdePage, name='nietverhuurd'),  
    # path('room/<str:pk>/', views.room, name="room"),
    # path('verhuurdaan/<str:pk>/<str:txt>/',views.verhuurdaan, name='verhuurdaan'),  
    # path('topics/', topicsPage, name="topics"),
    # path('verhuur/', verhuurPage, name="verhuur"),
    # path('', home, name='home'),
    # path('viking', home, name='home'),
    # path('update-user/', updateUser, name="update-user"),
    # path('register/', registerPage, name="register"),    
    # path('profile/<str:pk>/', userProfile, name='user-profile'),
    # path('create-vikinglid/', createVikinglid, name='create-vikinglid'),
    # path('mutatie/', mutatie, name='mutatie'),
    # path('delete-vikinglid/<str:pk>/', deleteVikinglid, name='delete-vikinglid'),
    #  path('kluislijst/', KluisList.as_view(), name='kluislijst'),
    # path('<str:pk>/update_kluis/<str:kol>/',update_kluis, name='update_kluis'),  
    # path('checkmatriks/', check_matriks, name='checkmatriks'),
    # path('hernummermatriks/', hernummermatriks, name='hernummermatriks'),
    # path('export/', file_load_view, name='export'),
    ]
# https://docs.djangoproject.com/en/3.1/topics/http/urls/